### ISSUE TITLE
Describe the TestLabDB solarbuildingenvelopes.com

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/database#41]
Please add the following description to https://www.solarbuildingenvelopes.com/ :

This is the website of the product data server of [TestLab Solar Facades](https://www.ise.fraunhofer.de/en/rd-infrastructure/accredited-labs/testlab-solar-facades.html) at [Fraunhofer Institute for Solar Energy Systems ISE](https://www.ise.fraunhofer.de/). The product data server is part of the Product Data Network [buildingenvelopedata.org](https://www.buildingenvelopedata.org/). The product data server is an instance of the [reference implementation of a database](https://github.com/building-envelope-data/database). The [reference implementation of a database](https://github.com/building-envelope-data/database) is open-source with a permissive license, so that everyone can easily create their own product data server as part of the Product Data Network [buildingenvelopedata.org](https://www.buildingenvelopedata.org/).

This website is the frontend of the product data server of [TestLab Solar Facades](https://www.ise.fraunhofer.de/en/rd-infrastructure/accredited-labs/testlab-solar-facades.html). You can use this website to search this product data server for [optical data](https://www.solarbuildingenvelopes.com/data/optical), [calorimetric data](https://www.solarbuildingenvelopes.com/data/calorimetric) and [photovoltaic data](https://www.solarbuildingenvelopes.com/data/photovoltaic). If you would like to search the entire Product Data Network [buildingenvelopedata.org](https://www.buildingenvelopedata.org/), you can search there for example for [optical data](https://www.buildingenvelopedata.org/data/optical). You will find there also an overview about all building envelope [components](https://www.buildingenvelopedata.org/components), [institutions](https://www.buildingenvelopedata.org/institutions), [data formats](https://www.buildingenvelopedata.org/data-formats), [methods](https://www.buildingenvelopedata.org/methods) and [databases](https://www.buildingenvelopedata.org/databases) of the Product Data Network [buildingenvelopedata.org](https://www.buildingenvelopedata.org/).

This website is completely based on the [GraphQL endpoint](https://www.solarbuildingenvelopes.com/graphql/). The [GraphQL endpoint](https://www.solarbuildingenvelopes.com/graphql/) is the Application Programming Interface (API) to the backend of the product data server. If you like programming, you can use the endpoint to automate the interaction with this product data server. You find the [specification of the API on GitHub](https://github.com/building-envelope-data/api) which is especially helpful if you develop software to plan buildings. The [GraphQL endpoint of the metabase](https://www.buildingenvelopedata.org/graphql/) is then a convenient way to query for data, components, institutions, databases, data formats and methods.

The data format [BED-JSON](https://www.buildingenvelopedata.org/data-formats/9ca9e8f5-94bf-4fdd-81e3-31a58d7ca708) is a general format for optical, calorimetric and photovoltaic data sets. It is defined by the [JSON Schemas of the API specification](https://github.com/building-envelope-data/api/tree/develop/schemas). Other [data formats](https://www.buildingenvelopedata.org/data-formats) are available, too.

![overview](https://user-images.githubusercontent.com/33456252/232802097-ac6f8045-3ef4-44c0-853a-b1de229f51e9.png)

**Comment by simonwacker** [comment]
Superseded by #42
