### ISSUE TITLE
Enable queries for `uValues`

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/database#54]
When I query https://www.solarbuildingenvelopes.com/graphql/ with
```
query {
  allCalorimetricData() {
    edges {
      node {
        uuid
        uValues
      }
    }
  }
}
```
I receive several data sets with a U value greater than 0.1. When I query with
```
query {
  allCalorimetricData(
    where: { uValues: { some: { greaterThanOrEqualTo: 0.1 } } }
  ) {
    edges {
      node {
        uuid
      }
    }
  }
}
```
I don't get a result. I have the same problem in the frontend https://www.solarbuildingenvelopes.com/data/calorimetric .

**Comment by simonwacker** [comment]
It works now. I don't know which commit fixed it.
