### ISSUE TITLE
Update resource of optical data set

### ISSUE THREAD

**Issue by christoph-maurer** [building-envelope-data/database#61]
When I try to update the optical data set e068d8f9-9e2c-4695-b5fc-16992041040f , I enter the access token and this UUID. But when I get the resource with the locator https://www.solarbuildingenvelopes.com/api/resources/9942026b-b9a2-4b4e-b9a0-5ba64f5a2eef , I still get the old file, even with google inspector and network cache disabled.

The log on the server looks good, too:
```
backend-1   | [08:47:03 INF] HTTP POST /api/upload-file responded 400 in 108.5860 ms
nginx-1     | 172.18.0.1 - - [04/Jul/2024:08:47:03 +0000] "POST /api/upload-file?getHttpsResourceUuid=e068d8f9-9e2c-4695-b5fc-16992041040f HTTP/1.0" 400 107 "https://www.solarbuildingenvelopes.com/upload-file" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "109.192.195.202"
backend-1   | [08:47:16 INF] HTTP GET /health responded 200 in 9.4049 ms
```

**Comment by simonwacker** [comment]
Well, no, the logs do not look good. It says that `.../upload-file` responded with status code 400, which means `bad request`, see for example https://http-status-code.de/400/ So, the upload doesn't work in the first place and that is why you get the old file. Now I need to figure out why the upload fails.

**Comment by christoph-maurer** [comment]
Thank you, @simon-wacker !

I have created the new optical data set 69ac98fb-3eb5-42d6-842f-ce1b4b314a05 . e068d8f9-9e2c-4695-b5fc-16992041040f already has a resource, 69ac98fb-3eb5-42d6-842f-ce1b4b314a05 not yet. When I try to upload the resource, I receive the following log:
```
backend-1   | [13:59:23 INF] HTTP GET /health responded 200 in 7.3926 ms
nginx-1     | 2024/07/04 13:59:31 [error] 33#33: *38403 open() "/data/files/4efd23f5-5b93-45dd-be17-e140a934c287" failed (2: No such file or directory), client: 172.18.0.1, server: , request: "GET /api/resources/4efd23f5-5b93-45dd-be17-e140a934c287 HTTP/1.0", host: "www.solarbuildingenvelopes.com", referrer: "https://www.solarbuildingenvelopes.com/data/optical"
nginx-1     | 172.18.0.1 - - [04/Jul/2024:13:59:31 +0000] "GET /api/resources/4efd23f5-5b93-45dd-be17-e140a934c287 HTTP/1.0" 404 548 "https://www.solarbuildingenvelopes.com/data/optical" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "109.192.195.202"
nginx-1     | 2024/07/04 13:59:38 [error] 33#33: *38404 open() "/data/files/4efd23f5-5b93-45dd-be17-e140a934c287" failed (2: No such file or directory), client: 172.18.0.1, server: , request: "GET /api/resources/4efd23f5-5b93-45dd-be17-e140a934c287 HTTP/1.0", host: "www.solarbuildingenvelopes.com", referrer: "https://www.solarbuildingenvelopes.com/data/optical"
nginx-1     | 172.18.0.1 - - [04/Jul/2024:13:59:38 +0000] "GET /api/resources/4efd23f5-5b93-45dd-be17-e140a934c287 HTTP/1.0" 404 548 "https://www.solarbuildingenvelopes.com/data/optical" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "109.192.195.202"
backend-1   | [13:59:53 INF] HTTP GET /health responded 200 in 8.0567 ms
```

**Comment by simonwacker** [comment]
I cannot reproduce the error. When the access token is correct, the UUID is the UUID of a resource (and not a data set), the file has a supported format, and the file extension matches that format, then I can upload files locally, in staging, and in production seamlessly. The logs you provided are not the ones of interest. Could you navigate to https://www.solarbuildingenvelopes.com/upload-file, open the Developer Tools, navigate to the "Network" tab within these tools, fill-out the form and select a file. Then, in the network tab there is a new POST request entry (supposedly with status code 400 if it still does not work for you). Click on that entry. And then click on the tab "Response" that corresponds to that entry. What does it say? Possible responses on error are among others "The access token ... is invalid." or "The file type isn't permitted or the file's signature doesn't match the file's extension.". Please post the error you get here. Or we may debug it together on our next meeting.

**Comment by christoph-maurer** [comment]
I'm sorry. I forgot the difference between the UUID of the data set and the UUID of the resource or made a mistake when I tried. With the UUID of resource, it works seamlessly.
